### ISSUE TITLE
Support for C++ syntax

### ISSUE THREAD

**Issue by UltraBlackLinux** [UMRnInside/MlogEvo#2]
Hey there,
I just found this and it may very well be the first instance of being able to use C for scripting, like ever.

I'm amazed that somebody actually attempted to do something like this, and now I'm wondering (as I'm sadly only familiar with C++), if you could add support for the c++ feature set. I know it is quite more advanced, or well, different, but I feel that that would be really cool.

What do you think?

Thanks!

**Comment by UMRnInside** [comment]
In most cases C++-familiar programmers should also be familiar with C. Most scripting works in Mindustry do not require Object-Oriented features (mainly Inheritance and Polymorphism), either.

As for C++ feature set... Well, parsing C++ is not as easy as parsing C: A LALR(1) parser can handle C grammar, but it cannot handle C++ grammar. MlogEvo depends on [PyCParser](https://github.com/eliben/pycparser/) to parse C code,  [which does not support C++](https://github.com/eliben/pycparser/wiki/FAQ#what-about-parsing-c). 

In my opinion, it is even easier to rely on [Clang (w/ Python binding)](https://eli.thegreenplace.net/2011/07/03/parsing-c-in-python-with-clang/). Or invoke `clang++` directly to generate LLVM IR, then generate Mlog code from LLVM IR.

**Comment by UltraBlackLinux** [comment]
Well, I'm the exception then. I have no prior experience with C. 

So, from what I could gather from your reply, it should be possible to compile C++ to Mlog with tools that already exist right?
I'm seeing an issue though. You said OOPL stuff won't work, but what about helper classes like Strings (The simplest one I could come up with)? Would that already cause issues? What about more complex stuff like iterators or foreaches and stuff?

**Comment by UMRnInside** [comment]
> So, from what I could gather from your reply, it should be possible to compile C++ to Mlog with tools that already exist right?

Sadly, such tools haven't appeared (as far as I know). It's *theoretically* possible to convert LLVM IR into Mlog. However, I see nobody working on this.

> but what about helper classes like Strings (The simplest one I could come up with)?

Well, Mlog *does* support strings, and it *just supports* strings: one cannot even concatenate strings in Mlog. There is a mod called [deltanedas/anuke-logic](https://github.com/deltanedas/anuke-logic) which adds string manipulation.

Helper classes appear neat (and simple), for lots of programmers, engineers, designers, sometimes mathematicians, have had tons of dirty work done. 

> What about more complex stuff like iterators or foreaches and stuff?

Iterators are associated with (and usually used on) [Containers](https://en.cppreference.com/w/cpp/container). The same for `foreach`.

**Comment by UltraBlackLinux** [comment]
hm oh well. Maybe anuken works on something like this one day. Thanks for clearing this up!

**Comment by k88936** [comment]
https://github.com/Mindustack/llvmir2mlog

im spending a hard time on it ,but i have to say one simple simple malloc as standard library would cost 250+ lines in mlog that is our nightmare,however,at least it is possible

**Comment by UltraBlackLinux** [comment]
didn't even know that was possible! Awesome!
