### ISSUE TITLE
If true statements or assigning won't be run on a certain case

### ISSUE THREAD

**Issue by kenjiuno** [UMRnInside/MlogEvo#3]
I'm writing a mlogevo code to: find injured first `@antumbra`, and send it to the nearest link point. Wait for recovery, and then send back to initial position.

I noticed that my `findNearestLinkFrom` func won't work as expected.

This is shorten for repro:

```c
#include <mlogevo/everything.h>

extern struct MlogObject message1;

void main()
{
    float len = 9999;
    float test_len = 99; // originally it is: hypot(x - point->x, y - point->y)
    if (test_len < len)
    {
        len = test_len;
    }
    print(len, " should be ", test_len);
    print_flush(message1);
    halt();
}
```

The result print should be `99 shouldbe 99`.

![2023-05-21_17h53_06](https://github.com/UMRnInside/MlogEvo/assets/5955540/5fbcdb49-506b-4a3d-a2c7-6c1c172f9116)

---

`-O 1` mlog (by default)

```sh
$ mlogevo o1_drop.c
```

```
set _len@main 9999
set _test_len@main 99
jump 3 greaterThanEq _test_len@main _len@main
print _len@main
print " should be "
print _test_len@main
printflush message1
stop
end
```

![2023-05-21_17h53_53](https://github.com/UMRnInside/MlogEvo/assets/5955540/88f2a3eb-2070-43b1-bf61-306333ad26ed)

---

`-O 0` mlog

```sh
$ mlogevo -O 0 o1_drop.c
```

![2023-05-21_17h53_06](https://github.com/UMRnInside/MlogEvo/assets/5955540/9a38cb26-ea46-4dbc-97a4-b48fadd71a98)

```
set _len@main 9999
set _test_len@main 99
jump 4 greaterThanEq _test_len@main _len@main
set _len@main _test_len@main
print _len@main
print " should be "
print _test_len@main
set _message_board@print_flush message1
printflush _message_board@print_flush
stop
end
```

**Comment by UMRnInside** [comment]
Reproduced this bug in MlogEvo 0.0.9 from PyPI. I fixed this bug in comit https://github.com/UMRnInside/MlogEvo/commit/8ba27363978eea6afb6b6c03170b51c7a7bfbbec . However, I forgot uploading that to pip.

You can run `pip install git+https://github.com/umrninside/mlogevo` to fix this ( or `pip install -U mlogevo`, I uploaded version 0.0.10 to PyPI just now)

**Comment by kenjiuno** [comment]
Thanks, version 0.0.10 from PyPI worked in my case!
